### PR TITLE
[BCHDCC-78] Add more Distance Intervals to Radius Search

### PR DESCRIPTION
**Pull request by emmabjj**
## Description

As a user, I want more distance intervals to appear as choices in my radius search.

Not all resources have an associated location, therefore the largest radius distance interval will not show all the results that you might have access to without using the location parameter search.

## Motivation and Context

[BCHDCC-78](https://app.clickup.com/t/9006094761/BCHDCC-78) - Add more distance intervals

Notes to manually test search accuracy
- Add a location zip code (e.g. 21225) to the location search input
- Select "1 mile" in the Radius dropdown and select the "Apply Filters" button 
- Compare the number of search results found as you increase the radius distance

_Note: Not all resources have an associated location, therefore the largest radius distance interval will not show all the results that you might have access to without using the location parameter search_ 

## Screenshots

Screenshot 2024-09-26 at 12 48 52 PM

**Libraries Added**

## Internal Checklist

- [ ] My code follows the code style of this project (https://rubystyle.guide/).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by anna-dorigo — COMMENTED** [review]
I can see the additional option on the drop down menu but I don't thing the filter is working, I see the same amount of results regardless of the distance. 

I confirmed and it is not working on production either, probably this needs to be fixed as part of this ticket? or maybe open a new one?

**Comment by emmabjj** [comment]
> I can see the additional option on the drop down menu but I don't thing the filter is working, I see the same amount of results regardless of the distance.
> 
> I confirmed and it is not working on production either, probably this needs to be fixed as part of this ticket? or maybe open a new one?

That's really strange, it works in my local env. Did you add a location zip code before changing the radius? Did you press "Apply Filters" at the bottom? Just checking, I forgot both of those at one point while testing this. 

Screenshot 2024-09-30 at 2 36 45 PM
Screenshot 2024-09-30 at 2 37 29 PM
Screenshot 2024-09-30 at 2 37 16 PM
Screenshot 2024-09-30 at 2 37 01 PM

**Review by anna-dorigo — APPROVED** [review]
I see!! my bad, I didn't see that it is "Within Of Address or Zip Code", I kind of thought it was taking the city center as point of reference. Well this works, I wonder if maybe an error message that you need to put a zip code for this to work would be a good idea, but maybe not part of this ticket.

**Comment by emmabjj** [comment]
> I see!! my bad, I didn't see that it is "Within Of Address or Zip Code", I kind of thought it was taking the city center as point of reference. Well this works, I wonder if maybe an error message that you need to put a zip code for this to work would be a good idea, but maybe not part of this ticket.

Okay great, glad it works! Error message is a good idea, I can add a comment for this to the error suggestions ticket (BCHDCC-72) 👍

**Pull request merged**
